export MKL_NUM_THREADS=12
export OMP_NUM_THREADS=12
export VECLIB_MAXIMUM_THREADS=12

build/IPC_bin 100 input/otherExamples/barTwist_noCollisions.txt --numThreads 12 -o test-out/barTwist_noCollisions.txt
build/IPC_bin 100 input/otherExamples/tunnel.txt --numThreads 12 -o test-out/tunnel.txt
build/IPC_bin 100 input/paperExamples/16_armaRoller_E1e5.txt --numThreads 12 -o test-out/16_armaRoller_E1e5.txt
build/IPC_bin 100 input/paperExamples/15_trashComp_shapes.txt --numThreads 12 -o test-out/15_trashComp_shapes.txt
build/IPC_bin 100 input/paperExamples/tb1_diffDt/rodsTwist_E1e4_dt2.txt --numThreads 12 -o test-out/rodsTwist_E1e4_dt2.txt
build/IPC_bin 100 input/paperExamples/tb1_diffDt/rodsTwist_E1e4_dt0.2.txt --numThreads 12 -o test-out/rodsTwist_E1e4_dt0.2.txt
build/IPC_bin 100 input/paperExamples/videoExamples/chain10.txt --numThreads 12 -o test-out/chain10.txt
build/IPC_bin 100 input/paperExamples/21_scalability/mat40x40_twist.txt --numThreads 12 -o test-out/mat40x40_twist.txt
build/IPC_bin 100 input/otherExamples/coDimUnitTests/octocat_squarePlaneDrop.txt --numThreads 12 -o test-out/octocat_squarePlaneDrop.txt
build/IPC_bin 100 input/otherExamples/coDimUnitTests/mat40x40_segPlaneDrop.txt --numThreads 12 -o test-out/mat40x40_segPlaneDrop.txt
build/IPC_bin 100 input/paperExamples/22_squishyBall.txt --numThreads 12 -o test-out/22_squishyBall.txt
build/IPC_bin 100 input/paperExamples/supplementB/Utopia/utopiaComparison.txt --numThreads 12 -o test-out/utopiaComparison.txt
build/IPC_bin 100 input/paperExamples/supplementB/SQPBenchmark/16_tetsCornerCO.txt --numThreads 12 -o test-out/16_tetsCornerCO.txt
build/IPC_bin 100 input/paperExamples/supplementB/SQPBenchmark/27_chain.txt --numThreads 12 -o test-out/27_chain.txt
build/IPC_bin 100 input/paperExamples/tb1_diffDt/rodsTwist_E1e4_dt0.5.txt --numThreads 12 -o test-out/rodsTwist_E1e4_dt0.5.txt
build/IPC_bin 100 input/paperExamples/tb1_diffDt/rodsTwist_E1e4_dt0.05.txt --numThreads 12 -o test-out/rodsTwist_E1e4_dt0.05.txt
build/IPC_bin 100 input/paperExamples/videoExamples/chain100.txt --numThreads 12 -o test-out/chain100.txt
build/IPC_bin 100 input/paperExamples/videoExamples/armaRoller_stickSlip.txt --numThreads 12 -o test-out/armaRoller_stickSlip.txt
build/IPC_bin 100 input/paperExamples/21_scalability/armadillo13K_twist.txt --numThreads 12 -o test-out/armadillo13K_twist.txt
build/IPC_bin 100 input/paperExamples/21_scalability/armadillo54K_twist.txt --numThreads 12 -o test-out/armadillo54K_twist.txt
build/IPC_bin 100 input/paperExamples/21_scalability/armadillo219K_twist.txt --numThreads 12 -o test-out/armadillo219K_twist.txt
build/IPC_bin 100 input/paperExamples/21_scalability/mat225x225_twist.txt --numThreads 12 -o test-out/mat225x225_twist.txt
build/IPC_bin 100 input/paperExamples/21_scalability/armadillo122K_twist.txt --numThreads 12 -o test-out/armadillo122K_twist.txt
build/IPC_bin 100 input/paperExamples/21_scalability/armadillo28K_twist.txt --numThreads 12 -o test-out/armadillo28K_twist.txt
build/IPC_bin 100 input/tutorialExamples/advanced/2cubesFall_BE.txt --numThreads 12 -o test-out/2cubesFall_BE.txt
build/IPC_bin 100 input/tutorialExamples/advanced/2cubesFall_rotateCO_meshSeq.txt --numThreads 12 -o test-out/2cubesFall_rotateCO_meshSeq.txt
build/IPC_bin 100 input/tutorialExamples/MCO/2cubesFall_rotateCO_closedSurface.txt --numThreads 12 -o test-out/2cubesFall_rotateCO_closedSurface.txt
build/IPC_bin 100 input/tutorialExamples/MCO/2cubesFall_rotateCO.txt --numThreads 12 -o test-out/2cubesFall_rotateCO.txt
build/IPC_bin 100 input/tutorialExamples/MCO/2cubesFall_rotateCO_triangle.txt --numThreads 12 -o test-out/2cubesFall_rotateCO_triangle.txt
build/IPC_bin 100 input/tutorialExamples/MCO/2cubesFall_rotateCO_points.txt --numThreads 12 -o test-out/2cubesFall_rotateCO_points.txt
build/IPC_bin 100 input/tutorialExamples/BC/2cubesFall_NBC_timeRange.txt --numThreads 12 -o test-out/2cubesFall_NBC_timeRange.txt
build/IPC_bin 100 input/tutorialExamples/BC/2cubesFall_DBC_timeRange.txt --numThreads 12 -o test-out/2cubesFall_DBC_timeRange.txt
build/IPC_bin 100 input/failures/SQPMemoryIssue4.txt --numThreads 12 -o test-out/SQPMemoryIssue4.txt
build/IPC_bin 100 input/failures/GurobiIncomplete.txt --numThreads 12 -o test-out/GurobiIncomplete.txt
build/IPC_bin 100 input/otherExamples/typical/rodsTwist.txt --numThreads 12 -o test-out/rodsTwist.txt
build/IPC_bin 100 input/otherExamples/typical/2matsFall.txt --numThreads 12 -o test-out/2matsFall.txt
build/IPC_bin 100 input/paperExamples/supplementB/SQPBenchmark/28_rodPlaneCO.txt --numThreads 12 -o test-out/28_rodPlaneCO.txt
build/IPC_bin 100 input/paperExamples/supplementB/SQPBenchmark/11_cubes.txt --numThreads 12 -o test-out/11_cubes.txt
build/IPC_bin 100 input/paperExamples/videoExamples/chain35.txt --numThreads 12 -o test-out/chain35.txt
build/IPC_bin 100 input/paperExamples/videoExamples/chain5.txt --numThreads 12 -o test-out/chain5.txt
build/IPC_bin 100 input/paperExamples/21_scalability/mat100x100_twist.txt --numThreads 12 -o test-out/mat100x100_twist.txt
build/IPC_bin 100 input/paperExamples/21_scalability/mat150x150_twist.txt --numThreads 12 -o test-out/mat150x150_twist.txt
build/IPC_bin 100 input/otherExamples/typical/sphere1K_segBedSquash.txt --numThreads 12 -o test-out/sphere1K_segBedSquash.txt
build/IPC_bin 100 input/otherExamples/typical/sphere1K_DCORotCylinders.txt --numThreads 12 -o test-out/sphere1K_DCORotCylinders.txt
build/IPC_bin 100 input/paperExamples/tb1_diffDt/rodsTwist_E1e4_dt0.005.txt --numThreads 12 -o test-out/rodsTwist_E1e4_dt0.005.txt
build/IPC_bin 100 input/paperExamples/videoExamples/heavyBallHit.txt --numThreads 12 -o test-out/heavyBallHit.txt
build/IPC_bin 100 input/tutorialExamples/MCO/2cubesFall_rotateCO_edges.txt --numThreads 12 -o test-out/2cubesFall_rotateCO_edges.txt
build/IPC_bin 100 input/tutorialExamples/MCO/2cubesFall_translateCO.txt --numThreads 12 -o test-out/2cubesFall_translateCO.txt
build/IPC_bin 100 input/tutorialExamples/initVel/2cubesFall_initVel.txt --numThreads 12 -o test-out/2cubesFall_initVel.txt
build/IPC_bin 100 input/tutorialExamples/initVel/2cubesFall_initRot.txt --numThreads 12 -o test-out/2cubesFall_initRot.txt
build/IPC_bin 100 input/otherExamples/typical/mat40x40Twist.txt --numThreads 12 -o test-out/mat40x40Twist.txt
build/IPC_bin 100 input/otherExamples/varyResolution/bar-test.txt --numThreads 12 -o test-out/bar-test.txt
build/IPC_bin 100 input/paperExamples/videoExamples/tightFitCube.txt --numThreads 12 -o test-out/tightFitCube.txt
build/IPC_bin 100 input/paperExamples/videoExamples/hitLargeCardHouse.txt --numThreads 12 -o test-out/hitLargeCardHouse.txt
build/IPC_bin 100 input/failures/SQPMemoryIssue2.txt --numThreads 12 -o test-out/SQPMemoryIssue2.txt
build/IPC_bin 100 input/failures/SQPMemoryIssue1.txt --numThreads 12 -o test-out/SQPMemoryIssue1.txt
build/IPC_bin 100 input/otherExamples/coDimUnitTests/sphere5K_pointPlaneDrop.txt --numThreads 12 -o test-out/sphere5K_pointPlaneDrop.txt
build/IPC_bin 100 input/otherExamples/coDimUnitTests/octocat_segPlaneDrop.txt --numThreads 12 -o test-out/octocat_segPlaneDrop.txt
build/IPC_bin 100 input/paperExamples/17_pinCushionBall.txt --numThreads 12 -o test-out/17_pinCushionBall.txt
build/IPC_bin 100 input/paperExamples/1_squeezeOut.txt --numThreads 12 -o test-out/1_squeezeOut.txt
build/IPC_bin 100 input/tutorialExamples/advanced/2cubesFall_NM.txt --numThreads 12 -o test-out/2cubesFall_NM.txt
build/IPC_bin 100 input/tutorialExamples/advanced/2cubesFall_attach.txt --numThreads 12 -o test-out/2cubesFall_attach.txt
build/IPC_bin 100 input/tutorialExamples/BC/2cubesFall_NBC.txt --numThreads 12 -o test-out/2cubesFall_NBC.txt
build/IPC_bin 100 input/tutorialExamples/BC/2cubesFall_DBC.txt --numThreads 12 -o test-out/2cubesFall_DBC.txt
build/IPC_bin 100 input/failures/GurobiException.txt --numThreads 12 -o test-out/GurobiException.txt
build/IPC_bin 100 input/failures/SQPMemoryIssue3.txt --numThreads 12 -o test-out/SQPMemoryIssue3.txt
build/IPC_bin 100 input/otherExamples/coDimUnitTests/mat40x40_pointPlaneDrop.txt --numThreads 12 -o test-out/mat40x40_pointPlaneDrop.txt
build/IPC_bin 100 input/otherExamples/varyYoungs/2_mat40x40s_fall_E1e4.txt --numThreads 12 -o test-out/2_mat40x40s_fall_E1e4.txt
build/IPC_bin 100 input/paperExamples/18_segRollerBall.txt --numThreads 12 -o test-out/18_segRollerBall.txt
build/IPC_bin 100 input/paperExamples/18_pointRollerBall.txt --numThreads 12 -o test-out/18_pointRollerBall.txt
build/IPC_bin 100 input/otherExamples/friction/matHouse_sharp.txt --numThreads 12 -o test-out/matHouse_sharp.txt
build/IPC_bin 100 input/otherExamples/friction/matHouse_sharp0.2.txt --numThreads 12 -o test-out/matHouse_sharp0.2.txt
build/IPC_bin 100 input/paperExamples/tb1_diffDt/rodsTwist_E1e4_dt0.1.txt --numThreads 12 -o test-out/rodsTwist_E1e4_dt0.1.txt
build/IPC_bin 100 input/paperExamples/tb1_diffDt/rodsTwist_E1e4_dt0.025.txt --numThreads 12 -o test-out/rodsTwist_E1e4_dt0.025.txt
build/IPC_bin 100 input/otherExamples/varyYoungs/2_mat40x40s_fall_E1e6.txt --numThreads 12 -o test-out/2_mat40x40s_fall_E1e6.txt
build/IPC_bin 100 input/otherExamples/ccd/somethingPlane.txt --numThreads 12 -o test-out/somethingPlane.txt
build/IPC_bin 100 input/paperExamples/supplementB/SQPBenchmark/30_matTwist.txt --numThreads 12 -o test-out/30_matTwist.txt
build/IPC_bin 100 input/paperExamples/supplementB/SQPBenchmark/29_cowHeadPlaneCO.txt --numThreads 12 -o test-out/29_cowHeadPlaneCO.txt
build/IPC_bin 100 input/paperExamples/tb1_diffDt/rodsTwist_E1e4_dt0.01.txt --numThreads 12 -o test-out/rodsTwist_E1e4_dt0.01.txt
build/IPC_bin 100 input/paperExamples/tb1_diffDt/rodsTwist_E1e4_dt0.002.txt --numThreads 12 -o test-out/rodsTwist_E1e4_dt0.002.txt
build/IPC_bin 100 input/otherExamples/coDimUnitTests/mat40x40_squarePlaneDrop.txt --numThreads 12 -o test-out/mat40x40_squarePlaneDrop.txt
build/IPC_bin 100 input/otherExamples/coDimUnitTests/sphere5K_squarePlaneDrop.txt --numThreads 12 -o test-out/sphere5K_squarePlaneDrop.txt
build/IPC_bin 100 input/paperExamples/15_trashComp_octocat.txt --numThreads 12 -o test-out/15_trashComp_octocat.txt
build/IPC_bin 100 input/paperExamples/19_golfBall.txt --numThreads 12 -o test-out/19_golfBall.txt
build/IPC_bin 100 input/otherExamples/ccd/matTwist.txt --numThreads 12 -o test-out/matTwist.txt
build/IPC_bin 100 input/otherExamples/ccd/torusCone.txt --numThreads 12 -o test-out/torusCone.txt
build/IPC_bin 100 input/paperExamples/8_rollerBall.txt --numThreads 12 -o test-out/8_rollerBall.txt
build/IPC_bin 100 input/paperExamples/14_matTwist.txt --numThreads 12 -o test-out/14_matTwist.txt
build/IPC_bin 100 input/paperExamples/11_erleben/spikeCrackCO.txt --numThreads 12 -o test-out/spikeCrackCO.txt
build/IPC_bin 100 input/paperExamples/tb1_diffDt/rodsTwist_E1e4_dt1.txt --numThreads 12 -o test-out/rodsTwist_E1e4_dt1.txt
build/IPC_bin 100 input/otherExamples/coDimUnitTests/sphere5K_segPlaneDrop.txt --numThreads 12 -o test-out/sphere5K_segPlaneDrop.txt
build/IPC_bin 100 input/otherExamples/coDimUnitTests/octocat_pointPlaneDrop.txt --numThreads 12 -o test-out/octocat_pointPlaneDrop.txt
build/IPC_bin 100 input/paperExamples/13_dolphinFunnel.txt --numThreads 12 -o test-out/13_dolphinFunnel.txt
build/IPC_bin 100 input/paperExamples/2_spherePoints.txt --numThreads 12 -o test-out/2_spherePoints.txt
build/IPC_bin 100 input/otherExamples/friction/masonryArch_25.txt --numThreads 12 -o test-out/masonryArch_25.txt
build/IPC_bin 100 input/otherExamples/friction/masonryArch_25_0.2.txt --numThreads 12 -o test-out/masonryArch_25_0.2.txt
build/IPC_bin 100 input/otherExamples/varyYoungs/2_mat40x40s_fall_E1e2.txt --numThreads 12 -o test-out/2_mat40x40s_fall_E1e2.txt
build/IPC_bin 100 input/otherExamples/varyYoungs/2_mat40x40s_fall_E1e8.txt --numThreads 12 -o test-out/2_mat40x40s_fall_E1e8.txt
build/IPC_bin 100 input/paperExamples/supplementB/SQPBenchmark/23_ErlebenSlidingSpike.txt --numThreads 12 -o test-out/23_ErlebenSlidingSpike.txt
build/IPC_bin 100 input/paperExamples/supplementB/SQPBenchmark/21_ErlebenSpikeCrack.txt --numThreads 12 -o test-out/21_ErlebenSpikeCrack.txt
build/IPC_bin 100 input/otherExamples/ccd/octocatBowl.txt --numThreads 12 -o test-out/octocatBowl.txt
build/IPC_bin 100 input/otherExamples/ccd/octocatPlane.txt --numThreads 12 -o test-out/octocatPlane.txt
build/IPC_bin 100 input/paperExamples/supplementB/SQPBenchmark/03_edgeEdgeCO.txt --numThreads 12 -o test-out/03_edgeEdgeCO.txt
build/IPC_bin 100 input/paperExamples/11_erleben/cubeInternalEdgesCO.txt --numThreads 12 -o test-out/cubeInternalEdgesCO.txt
